import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="text-gray-600 bg-gradient-to-b from-slate-100 to-white">
				<nav className="w-full bg-white py-4 px-12 border-b flex justify-between items-center">
					Crypto Portfolio
					<button className="border rounded-lg py-2 px-5 hover:bg-gray-100">Connect Wallet</button>
				</nav>
				{children}
			</body>
		</html>
	);
}
